# Dockerfile.dev
FROM node:22-alpine

# Create app directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Enable hot-reloading with ts-node-dev
RUN npm install -g ts-node-dev

CMD ["ts-node-dev", "--respawn", "--transpile-only", "src/main.ts"]
